name: Push to GitHub Enterprise

on:
  push:
    branches:
      - main

jobs:
  push-to-enterprise:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Add GitHub Enterprise remote
        run: |
          git remote add enterprise "https://${{ secrets.ENTERPRISE_TOKEN }}@github.qmul.ac.uk/ec20746/dreamteam-web.git"

      - name: Force push to GitHub Enterprise
        run: |
          git push enterprise main --force
